stages:
  - pull-github
  - build
  - deploy

variables:
  GIT_STRATEGY: clone			#This seems to have no effect also set in webinterface
  GIT_DEPTH: 0					#This seems to have no effect also set in webinterface
  GIT_SUBMODULE_STRATEGY: recursive

pull:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
  image: ubuntu:20.04
  tags:
    - uind
  stage: pull-github
  before_script:
    - apt-get update -y
    - apt-get install -y git
  script:
    - mkdir git-magic
    - cd git-magic
    - git clone --mirror https://github.com/Nitrokey/pynitrokey.git
    - ls
    - cd pynitrokey
    - git remote add --mirror=fetch secondary https://git.dotplex.com/lennard.boediger/pynitrokey.git
    - git remote set-url secondary https://oauth2:$GITLAB_REPO_KEY@git.dotplex.com/lennard.boediger/pynitrokey.git
    - git fetch origin
    - git push secondary --tags
    - git push secondary --all